### ISSUE TITLE
Passing a custom prop

### ISSUE THREAD

**Issue by AdamBrodzinski** [kadirahq/meteor-reaktor#11]
Is there an easy way to pass props into the `Route`'s without creating a fork?

I'm using Redux and I need to pass a prop `store` into each `Route` or ideally once into `Router`. With FlowRouter + ReactLayout I could pass it in easily.

An example:

```
  <Router>
    <Route path="/" store={appState} content={Home} layout={Layout} />
  </Router>
```

I guess the easiest thing is to go back to FlowRouter :frowning:

**Comment by arunoda** [comment]
Yeah! It's not possible without a fork.

**Comment by AdamBrodzinski** [comment]
Thanks!
